### ISSUE TITLE
Refresh Button

### ISSUE THREAD

**Issue by EQ2Alyza** [TurBoss/7h#8]
Can we get a Refresh button added onto the Library and Catalog tabs? The Search button acts as the current refresh, but I get enough reports that say "Nothing shows up..." because they're unaware of the Search button acting as a refresh as well.

**Comment by TurBoss** [comment]
I can also add a autorefresh action on tab changed?

**Comment by EQ2Alyza** [comment]
Sure, that would be great.

**Comment by TurBoss** [comment]
Ok here they are

📦 [Debug.zip](https://github.com/TurBoss/7h/files/784806/Debug.zip)
📦 [Release.zip](https://github.com/TurBoss/7h/files/784805/Release.zip)

**Comment by EQ2Alyza** [comment]
I uninstalled the World Textures category from the Catalog, Downloaded it again, and now when I try to Activate it I get the following message:

System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at _7thWrapperLib.IrosArc.LzmaUncompress(Byte[] dest, Int32& destLen, Byte[] src, Int32& srcLen, Byte[] props, Int32 propsSize)
   at _7thWrapperLib.IrosArc.GetCache(DirectoryEntry e)
   at _7thWrapperLib.IrosArc.GetBytes(String name)
   at Iros._7th.Workshop.fLibrary.GetModInfo(InstalledItem ii)
   at Iros._7th.Workshop.fLibrary.ToggleActivateMod(Guid modID)
   at Iros._7th.Workshop.fLibrary.DoModBarAction(pMod pm, ModBarAction a)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by EQ2Alyza** [comment]
Just tried the same method with World Models - Vehicles and get the same error message again. I am not going to test this with all the categories. I assume it's going to happen to them all.

**Comment by TurBoss** [comment]
ok that was because a cpu arch mismatch ...

here are the new ones

📦 [Release.zip](https://github.com/TurBoss/7h/files/785840/Release.zip)
📦 [Debug.zip](https://github.com/TurBoss/7h/files/785841/Debug.zip)

**Comment by EQ2Alyza** [comment]
Good =)

Closing
